const S={employees:[],user:null,view:'login',selected:null,query:'',txType:null};
const TYPES=['غياب','إذن خروج','إجازة','استقالة'];
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function getTx(){try{return JSON.parse(localStorage.getItem('hr_transactions')||'[]')}catch{return[]}}
function saveTx(list){localStorage.setItem('hr_transactions',JSON.stringify(list))}
function toast(msg){const e=document.createElement('div');e.className='toast';e.textContent=msg;document.body.appendChild(e);setTimeout(()=>e.remove(),2200)}
function top(title,back=false){return `<div class="topbar"><div>${back?'<button class="linkbtn" id="backBtn">‹ رجوع</button>':''}</div><div class="brand">${esc(title)}</div><div>${S.user?'<button class="linkbtn" id="logoutBtn">خروج</button>':''}</div></div>`}
function wireCommon(){if($('#logoutBtn'))$('#logoutBtn').onclick=()=>{sessionStorage.removeItem('hr_auth');S.user=null;S.view='login';render()};if($('#backBtn'))$('#backBtn').onclick=()=>{S.view=S.selected?'employee':'home';if(S.view==='home')S.selected=null;render()}}
function loginView(){document.querySelector('#app').innerHTML=`<div class="app"><div class="container"><div class="card hero"><div class="logo">HR</div><h1 class="h1">HR Numbers</h1><p class="muted">النسخة التجريبية للموارد البشرية</p><div class="field" style="text-align:right"><label>رمز الدخول</label><input id="pin" inputmode="numeric" type="password" placeholder="أدخل الرمز" autocomplete="off"></div><button id="loginBtn" class="btn btn-primary">دخول</button><div id="loginErr" class="error"></div><p class="muted small">رمز النسخة التجريبية: 1234</p></div></div></div>`;$('#loginBtn').onclick=()=>{if($('#pin').value==='1234'){sessionStorage.setItem('hr_auth','1');S.user='HR';S.view='home';render()}else $('#loginErr').textContent='رمز الدخول غير صحيح'};$('#pin').addEventListener('keydown',e=>{if(e.key==='Enter')$('#loginBtn').click()})}
function homeView(){let q=S.query.trim().toLowerCase();let list=q?S.employees.filter(e=>String(e.id).includes(q)||(e.fullName||'').toLowerCase().includes(q)).slice(0,80):S.employees.slice(0,30);document.querySelector('#app').innerHTML=`<div class="app">${top('HR Numbers')}<div class="container"><div class="search"><div class="field"><input id="search" value="${esc(S.query)}" placeholder="ابحث برقم الموظف أو الاسم" inputmode="search"></div></div><div class="card"><div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:6px"><strong>الموظفون</strong><span class="badge">${S.employees.length} موظف</span></div><div id="results">${list.length?list.map(e=>`<div class="result" data-id="${e.id}"><div><div class="emp-name">${esc(e.fullName||'بدون اسم')}</div><div class="emp-meta">${esc(e.jobTitle||e.department||e.company||'')}</div></div><span class="badge">${esc(e.id)}</span></div>`).join(''):'<div class="empty">لا توجد نتائج</div>'}</div></div></div></div>`;wireCommon();$('#search').oninput=e=>{S.query=e.target.value;homeView();setTimeout(()=>{const i=$('#search');i.focus();i.setSelectionRange(i.value.length,i.value.length)},0)};document.querySelectorAll('.result').forEach(el=>el.onclick=()=>{S.selected=S.employees.find(x=>String(x.id)===el.dataset.id);S.view='employee';render()})}
function kv(k,v){return `<div class="kv"><div class="k">${k}</div><div class="v">${esc(v||'—')}</div></div>`}
function employeeView(){const e=S.selected;const tx=getTx().filter(t=>String(t.employeeId)===String(e.id)).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));document.querySelector('#app').innerHTML=`<div class="app">${top('ملف الموظف',true)}<div class="container"><div class="card"><div style="display:flex;justify-content:space-between;gap:12px;align-items:flex-start"><div><h2 style="margin:0 0 5px">${esc(e.fullName)}</h2><div class="muted">${esc(e.jobTitle||e.department||'')}</div></div><span class="badge">#${esc(e.id)}</span></div><div class="grid" style="margin-top:14px">${kv('القسم',e.department)}${kv('مكان العمل',e.workPlace)}${kv('منطقة العمل',e.workArea)}${kv('مكان السكن',e.livingPlace)}${kv('الجنسية',e.nationality)}${kv('الشركة',e.company)}${kv('انتهاء الإقامة',e.residenceExpiration)}${kv('الحالة',e.status)}</div></div><div class="card"><strong>تسجيل معاملة</strong><div class="actions" style="margin-top:12px">${TYPES.map(t=>`<button class="action" data-type="${t}">${t}</button>`).join('')}</div></div><div class="card"><strong>سجل المعاملات</strong>${tx.length?tx.map(t=>`<div class="tx"><div class="tx-title">${esc(t.type)} — ${esc(t.date)}</div><div class="tx-meta">${esc(t.duration||'')} ${t.reason?'• '+esc(t.reason):''}</div>${t.notes?`<div class="small" style="margin-top:5px">${esc(t.notes)}</div>`:''}</div>`).join(''):'<div class="empty">لا توجد معاملات مسجلة على هذا الجهاز</div>'}</div></div></div>`;wireCommon();document.querySelectorAll('.action').forEach(b=>b.onclick=()=>{S.txType=b.dataset.type;S.view='transaction';render()})}
function transactionView(){const e=S.selected;const d=new Date().toISOString().slice(0,10);document.querySelector('#app').innerHTML=`<div class="app">${top(S.txType,true)}<div class="container"><div class="card"><div class="muted">الموظف</div><div style="font-weight:850;margin-top:3px">${esc(e.fullName)} <span class="badge">#${esc(e.id)}</span></div></div><div class="card"><div class="field"><label>التاريخ</label><input id="date" type="date" value="${d}"></div><div class="field"><label>المدة / الساعات</label><input id="duration" placeholder="مثال: يوم واحد أو ساعتان"></div><div class="field"><label>السبب</label><input id="reason" placeholder="سبب المعاملة"></div><div class="field"><label>ملاحظات</label><textarea id="notes" rows="4" placeholder="ملاحظات إضافية"></textarea></div><button id="saveBtn" class="btn btn-primary">حفظ المعاملة</button></div></div></div>`;wireCommon();$('#saveBtn').onclick=()=>{const tx=getTx();tx.push({id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),employeeId:e.id,employeeName:e.fullName,type:S.txType,date:$('#date').value,duration:$('#duration').value.trim(),reason:$('#reason').value.trim(),notes:$('#notes').value.trim(),createdAt:new Date().toISOString()});saveTx(tx);toast('تم حفظ المعاملة');S.view='employee';render()}}
function render(){if(!S.user&&sessionStorage.getItem('hr_auth')==='1')S.user='HR';if(!S.user)return loginView();if(S.view==='home')homeView();else if(S.view==='employee'&&S.selected)employeeView();else if(S.view==='transaction'&&S.selected)transactionView();else{S.view='home';homeView()}}
render();
(async function(){try{const r=await fetch('./employees.json?v=11',{cache:'no-store'});if(!r.ok)throw new Error('employees '+r.status);S.employees=await r.json();if(S.user&&S.view==='home')render()}catch(e){console.error(e);S.employees=[];if(S.user&&S.view==='home')render()}})();
